# This workflow will run tests using node and then publish a nextjs website to an ec2 instance when a release is created

name: Deploy to EC2

on:
  push:
    branches:
      - master  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use an Ubuntu runner

    steps:
      - name: Get VPC IP
        id: vpc-ip
        uses: haythem/public-ip@v1.2

      - name: Add IP to AWS Security group
        id: add-ip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-southeast-2"
          IP: ${{ steps.vpc-ip.outputs.ipv4 }}/32
          DESC: 'Github'
          SG: ${{ secrets.EC2_INSTANCE_SECURITYGROUP}}
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id $SG \
            --ip-permissions IpProtocol=tcp,FromPort=22,ToPort=22,IpRanges="[{CidrIp=${IP},Description=${DESC}}]"

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/Github-Actions
          chmod 600 ~/.ssh/Github-Actions
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into EC2 and deploy
        run: |

          ssh -o StrictHostKeyChecking=no -i ~/.ssh/Github-Actions ubuntu@${{ secrets.EC2_INSTANCE_HOSTNAME}} 'bash -s' << 'EOF'
            cd /home/ubuntu/next-emenu
            git pull origin master  # Pull latest changes from main branch
            npm install            # Install dependencies
            npm run build          # Build Next.js app
            pm2 stop all           # Stop all existing PM2 processes
            pm2 start next --name "next-emenu" -- start -p 3001  # Start Next.js app with PM2
            sudo systemctl restart nginx  # Restart Nginx
          EOF

